package com.booking.tests;

import com.booking.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

public class GeneratedTests extends TestBase {

    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Check booking logo")
    void generatedTest() {
        step("Open https://www.booking.com/", () -> {
            step("// todo: just add selenium action");
        });

        step("Check booking logo is present", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.booking.com/'", () ->
                open("https://www.booking.com/"));

        step("Page title should have text 'Booking.com | Official site | The best hotels & accommodation'", () -> {
            String expectedTitle = "Booking.com | Official site | The best hotels & accommodations";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.booking.com/'", () ->
                open("https://www.booking.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}